### ISSUE TITLE
Doesn't work with Rails 3

### ISSUE THREAD

**Issue by iGEL** [ngauthier/hydra#13]
Sadly, it doesn't work with Rails 3 Beta 4. I get these errors:

> rake hydra:units
>   (in [...])
>   DEPRECATION WARNING: RAILS_ENV is deprecated! Use Rails.env instead. (called from /home/igel/.bundle/ruby/1.8/gems/hydra-0.19.4/lib/hydra/tasks.rb:108)
>   WARNING: RAILS_ENV is "development". Make sure to set it properly (ex: "RAILS_ENV=test rake hydra")
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   no such file to load -- test_helper  
>   Hydra Testing [##############################>] 19/19

Setting RAILS_ENV just removes the warning about being in dev environment.

My setup (On Ubuntu 10.4):

> rails --version
>   Rails 3.0.0.beta4
> gem --version
>   1.3.7
> ruby --version
>   ruby 1.8.7 (2010-01-10 patchlevel 249) [x86_64-linux]

**Comment by ngauthier** [comment]
I don't think this is Rails 3. Please see the first section of the FAQ:
http://wiki.github.com/ngauthier/hydra/why-isnt-it-working

**Comment by iGEL** [comment]
I tried that, to quote myself:
"Setting RAILS_ENV just removes the warning about being in dev environment."

**Comment by ngauthier** [comment]
Specifically, I'm referring to changing the "require 'test_helper'" to something more like:
    require File.join(File.pathname(**FILE**), '..', 'test_helper')

-Nick

**Comment by iGEL** [comment]
Hmm, look's like I havn't read the docs as I should. I'm don't have time to try it again, so I'll just close the bug for now.
