### ISSUE TITLE
Multiple runners and rspec fails?

### ISSUE THREAD

**Issue by joerichsen** [ngauthier/hydra#2]
Hi,

First of all, let me say that Hydra looks very promising. I want to use it on a project that has a 10+ minutes rspec suite runtime.

My hydra.yml looks like this:

workers:
    - type: local
      runners: 2

But I get the following stack trace:

http://gist.github.com/368120

If I change the number of runners to 1 it seems to work? Seems to be some transactional/db-issue?

/Jørgen

**Comment by ngauthier** [comment]
definitely a db issue. I am not familiar with ar-extentsion, but I would try to trace down exactly the error that is being raised (you did not include the actual exception in your gist).

I can help more if you are able to create a minimal example that you can send to me and I can run, but it could be difficult.

-Nick

**Comment by joerichsen** [comment]
I've tried to reproduce it in a minimal example but haven't succeeded yet. I'll reopen & update this issue if I succeed.

/Jørgen

**Comment by ngauthier** [comment]
Cool thanks Jørgen.

**Comment by joerichsen** [comment]
I just upgraded to 0.16.4 and the issues I saw with the earlier version are now gone :-)

/Jørgen

**Comment by ngauthier** [comment]
Awesome! It was a DB concurrency patch. It was actually for someone else (and it didn't help them). Glad it helped you!
