### ISSUE TITLE
RSpec 2 using #filter_run

### ISSUE THREAD

**Issue by lmarburger** [ngauthier/hydra#22]
Using [`filter_run`](http://blog.davidchelimsky.net/2010/06/14/filtering-examples-in-rspec-2/) in RSpec 2 causes Hydra to think the specs failed. I created a [skeleton app](http://github.com/lmarburger/hydra-rspec2-test) that works and [added branch using `filter_run`](http://github.com/lmarburger/hydra-rspec2-test/tree/rspec-filter-run) which always fails.

```
$ RAILS_ENV=test rake hydra
Run filtered using {:focused=>true}

Hydra Testing [##############################>] 1/1
rake aborted!
Hydra: Not all tests passes

(See full trace by running task with --trace)
```

Commenting [the line in RSpec that prints the filtered message](http://github.com/rspec/rspec-core/blob/v2.0.0.beta.19/lib/rspec/core/world.rb#L59) "fixes" the issue.

```
$ RAILS_ENV=test rake hydra
Hydra Testing [##############################>] 1/1
```

I'll gladly take a look. Any direction would be appreciated.

**Comment by ngauthier** [comment]
Glad you figured it out! :smile: :heart:

**Comment by lmarburger** [comment]
![celebrate](https://cloud.githubusercontent.com/assets/23582/5766576/b4d266a0-9cd0-11e4-954c-e3a801a0e278.gif)
