### ISSUE TITLE
Hydra not actually running tests on remote machine?

### ISSUE THREAD

**Issue by rodreegez** [ngauthier/hydra#30]
I can run global tasks locally and on the remote machine, I can sync the project to the remote machine. Hydra can create an ssh worker on the remote machine, but it just won't run any tests on the remote machine! They all run, but only locally.
- This is the hydra.yml file I am using: https://gist.github.com/740747
- This is the verbose output: https://gist.github.com/740759
- This is the test project I'm working on: https://github.com/Rodreegez/Hydra-test (it's a fudge)

I think the remote worker is dying shortly after being booted, and therefore not requesting files? Is this a bug?

EDIT: 'mini' is defined in ~/.ssh/config - it's a Mac Mini on the local network, which has my public key.

**Comment by ngauthier** [comment]
the remote worker stuff can be a bit flaky. Try configuring it with only a remote worker (no local worker). If it just hangs then the boot is failing.

Then you have to look at hydra's remote worker boot code and see what you need to run on the remote box to reproduce.

RVM can be an issue, I am not sure if your .rvmrc will get loaded. (If you're using it).

**Comment by rodreegez** [comment]
Thanks,

rm'd local runner, no joy. killed RVM on the remote, still no joy. 

investigating...

**Comment by rodreegez** [comment]
Managed to trace my way to here: https://github.com/ngauthier/hydra/blob/master/lib/hydra/master.rb#L206

We don't seem to be getting any messages... investigating...

**Comment by ngauthier** [comment]
try running this line:

https://github.com/ngauthier/hydra/blob/master/lib/hydra/master.rb#L175

after sshing into the remote system (replace environment with your test env)

**Comment by rodreegez** [comment]
Ah ha! 

I am setting the load path in hydra_worker_init.rb. I guess rails isn't loaded at this point.

https://github.com/Rodreegez/Hydra-test/blob/master/hydra_worker_init.rb

**Comment by ngauthier** [comment]
the rails env doesn't get loaded until your first test requires it in via test helpers. :-)

This is because Hydra is ruby code, and can work outside of rails. So it treats rails like any other library that is required. It's one of the big gotchas on hydra.

And "make remote debugging not suck" is one of the more requested features :-)

**Comment by rodreegez** [comment]
haha. yeah, I've been bitten by the rails thing more than once - hopefully this time I will learn.
