### ISSUE TITLE
adding hydra to gemfile breaks individual tests

### ISSUE THREAD

**Issue by josh-m-sharpe** [ngauthier/hydra#42]
1) add this:
group :test do
  ...
  gem 'hydra'
end
2) bundle
3) ruby test/unit/user_test.rb
4) get nothing
5) remove gem 'hydra'
6) bundle
7) ruby test/unit/user_test.rb
8) works like a charm

As expected 'rake hydra:units' doesn't work unless hydra is bundled - so it seems like it's an either or situation.  I don't think hydra should be blocking the execution of individual tests.

**Comment by ngauthier** [comment]
Try:

gem 'hydra', :require => false

Nick
On May 29, 2011 12:06 PM, "crankharder" <
reply@reply.github.com>
wrote:

**Comment by josh-m-sharpe** [comment]
This is the correct answer.

**Comment by ngauthier** [comment]
Awesome :-)
On May 29, 2011 2:03 PM, "crankharder" <
reply@reply.github.com>
wrote:
