### ISSUE TITLE
hydra and ci_reporter

### ISSUE THREAD

**Issue by rb2k** [ngauthier/hydra#47]
Not so much a bug as a feature request/question.
Is there any way that hydra could run with ci_reporter (https://github.com/nicksieger/ci_reporter) functionality enabled?
We're trying to set up a good integration with Jenkins, but since hydra replaces a lot of the rake functionality I'm not sure if this is possible or not.

**Comment by ngauthier** [comment]
About a year ago I we had an issue about CI:

https://github.com/ngauthier/hydra/issues/15

Making sure we return an appropriate exit code. Is the problem the exit
code? Or is hydra exiting the task and not allowing others to run? Or
something else?

Nick

**Comment by rb2k** [comment]
The ci_reporter gem basically hooks into rake and allows it to generate JUnit XML files for the tests.
I think the main problem is that hydra replaces a lot of what rake usually does. (right?)

**Comment by ngauthier** [comment]
Hydra doesn't replace any part of rake, it works with rake. Hydra helps
define a rake task that sets up the hydra master server.

https://github.com/ngauthier/hydra/blob/master/lib/hydra/tasks.rb#L119

So, if ci_reporter just runs rake tasks, that should be fine for hydra,
because it sets itself up as a rake task.

**Comment by rb2k** [comment]
Maybe the problem is the way that ci_reporter implements a test-unit runner mediator: https://github.com/nicksieger/ci_reporter/blob/master/lib/ci/reporter/test_unit.rb#L62 vs the way that hydra loads test-unit tests?

**Comment by ngauthier** [comment]
That is definitely the issue.

Other people who have used CI with Hydra used a CI that just ran scripts and used exit codes to determine success. ci_reported seems very ruby-specific. You may have not be able to integrate the two.

**Comment by rb2k** [comment]
Oh well, it was worth a try.
I guess we can close this one then
