### ISSUE TITLE
problem with erb in yaml? unsure.

### ISSUE THREAD

**Issue by ssoroka** [ngauthier/hydra#6]
Fixture::FormatError: a YAML error occurred parsing test/fixtures/whatever.yml.
The exact error was:
  ArgumentError: wrong number of arguments (4 for 1)
    vendor/rails/activerecord/lib/active_record/fixtures.rb:746:in `parse_yaml_string'

**Comment by ngauthier** [comment]
Don't use fixtures.

But if you must, it is better to load the fixtures ahead of time, not during your test task. So you have to run rake db:fixtures:load then disable fixtures in test helper then run hydra.

**Comment by ssoroka** [comment]
I wish I wasn't, trust me.  can't get around it right now.  Big project, would be massive effort to convert it.

**Comment by ngauthier** [comment]
Hey Steven,

I just fired up a test project with fixtures and I'm not having any trouble with YAML fixtures with ERB in them. Can you send me a failing example?
