### ISSUE TITLE
[Patch included] Rspec files with 'pending' tests results in the file reported as failed 

### ISSUE THREAD

**Issue by rud** [ngauthier/hydra#7]
Fix: HydraFormatter must also define the method example_pending(*args), and do nothing - similar to how dump_summary is defined.

**Comment by rud** [comment]
I've pushed a fix with specs here:

http://github.com/rud/hydra/tree/rspec-allow-pending-specs

**Comment by rud** [comment]
First version had a spec-failing typo. All fixed now

**Comment by ngauthier** [comment]
Awesome thanks! Your changes are now present in Hydra 0.16.5.

-Nick

**Comment by rud** [comment]
Thank you for the quick merge :)

## 

Laust Rud
